phases:
  install:
    commands:
      - "sudo yum update"
      - "curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.34.0/install.sh | bash"
      - ". ~/.nvm/nvm.sh"
      - "nvm install --lts"
      - "node -e "console.log('Running Node.js ' + process.version)""
      - "npm --version"
  build:
    commands:
    - "sudo npm install -g pm2"
    - "pm2 startup systemd -d killer --hp /homr/killer "
    - "pm2 -v"
    - "cd devops-code-challenge"
    - "cd backend"
    - "pm2 ci"
    - "pm2 start"
  build:
    commands:
    - "cd .."
    - "cd frontend"
    - "pm2 ci"
    - "pm2 start"
  post_build:
    commands:
      - echo welcome to my app on 'date'