phases:
  install:
    commands:
      - "sudo apt update"
      - "sudo apt install nodejs"
      - "node -v"
      - "node -e 'console.log('Running Node.js ' + process.version)'"
      - "sudo apt install npm"
      - "npm --version"
  build:
    commands:
    - "sudo npm install -g pm2"
    - "pm2 startup systemd -d killer --hp /homr/killer "
    - "pm2 -v"
    - "cd devops-code-challenge"
    - "cd backend"
    - "pm2 ci"
    - "pm2 start"
  build:
    commands:
    - "cd .."
    - "cd frontend"
    - "pm2 ci"
    - "pm2 start"
  post_build:
    commands:
      - echo welcome to my app on 'date'